apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: dev-project
  source:
    repoURL: https://ramdy1449.github.io/helm-charts
    chart: bank
    targetRevision: 0.2.8
    helm:
      values: |
        storage:
          storageClass: nfs-client
        
        public:
          gatewayUrl: "https://gateway.localtest.me"
          expenseUrl: "https://expense.localtest.me"
          chatUrl: "https://chat.localtest.me"
          bankUrl: "https://bank.localtest.me"
        
        ingress:
          enabled: true
          host: "bank.localtest.me"
  destination:
    server: https://kubernetes.default.svc
    namespace: bank
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true