apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://ramdy1449.github.io/helm-charts
    chart: bank
    targetRevision: 0.1.1
  destination:
    server: https://kubernetes.default.svc
    namespace: bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true