apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://ramdy1449.github.io/helm-charts
    chart: expense
    targetRevision: 0.2.7
  destination:
    server: https://kubernetes.default.svc
    namespace: expense
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true