apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: gateway 
  namespace: argocd 
spec: 
  project: global-project
  source: 
    repoURL: https://ramdy1449.github.io/helm-charts 
    chart: gateway 
    targetRevision: 0.1.2 
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway 
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 