apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec: 
  project: dev-project
  source: 
    repoURL: https://ramdy1449.github.io/helm-charts
    chart: longhorn 
    targetRevision: 0.1.0
  destination:
      server: https://kubernetes.default.svc
      namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 