apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: dev-project
  source:
    repoURL: https://ramdy1449.github.io/helm-charts
    chart: monitoring
    targetRevision: 0.1.14
    helm:
      values: |
        # Storage
        storage:
          storageClass: nfs-client
        
        # Ingress for all monitoring components
        ingress:
          enabled: true
          grafana:
            host: "grafana.localtest.me"
          prometheus:
            host: "prometheus.localtest.me"
          alertmanager:
            host: "alertmanager.localtest.me"
        
        # Grafana
        grafana:
          serviceName: grafana
          servicePort: 3000
        
        # Prometheus
        prometheus:
          serviceName: prometheus
          servicePort: 9090
        
        # Alertmanager
        alertmanager:
          enabled: false
          serviceName: alertmanager
          servicePort: 9093
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true